# Composicao do programa de teste de uma lista genérica duplamente encadeada circular
[Diretorios]

Nome        =  TesteListaC
PathDefault =  ..\Fonte
err         =  ..\Produto
obj         =  ..\Objetos
c           =  ..\Fonte
h           =  ..\Fonte

[Modulos]
LISTAC /D_DEBUG
TST_LISTAC /D_DEBUG

[BuildInicio]
/OUT:..\Produto\TesteListaC.exe
/INCREMENTAL:NO
/MACHINE:IX86

[BuildFim]
ArcaboucoTeste.lib

[Fim]
